language: ruby
rvm:
  - 2.4.3
  - jruby
services:
  - postgresql
addons:
  - psql "10.4"
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec test/
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
