# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae716a78e5454f6dc267ab7f18028cf159a0d9be71f6fb2ca5eb73214f180a74d1bdc76d20b75446c62dac1d47e1cf0986262265844417f06ce0ed4a6590039b

test:
  secret_key_base: b73802dc258da6fb8fae33dd3c96edd0d3da4495754f757671648e9d8f4df155fb259a4aa33b62cfdb173d54199996cbb36c623e88bd23f7c7fb389571e8d3a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
